actions: actions
web: web-src
operations:
  view:
    - type: web
      impl: index.html
runtimeManifest:
  packages:
    __APP_PACKAGE__:
      license: Apache-2.0
      actions:
        stock-search:
          function: actions/stock-search/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            stockApiKey: $STOCK_API_KEY
          annotations:
            require-adobe-auth: true
            final: true
        welcome-state:
          function: actions/welcome-state/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
        brief-save:
          function: actions/brief-save/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            apiKey: $YOUR-SERVICE_API_KEY
            providerId: $YOUR-PROVIDER_ID
            eventCode: $YOUR-EVENT_CODE
          annotations:
            require-adobe-auth: true
            final: true
        brief-list:
          function: actions/brief-list/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
        brief-create-event-handler:
          function: actions/brief-create-event-handler/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
        brief-delete:
          function: actions/brief-delete/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true