name: E2E test
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          spec: cypress/integration/welcome-view_spec.js
        env:
          CYPRESS_email: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}